# PD Configuration.

name = "pd"
data-dir = "default.pd"

client-urls = "http://127.0.0.1:2379"
# if not set, use ${client-urls}
advertise-client-urls = ""

peer-urls = "http://127.0.0.1:2380"
# if not set, use ${peer-urls}
advertise-peer-urls = ""

initial-cluster = "pd=http://127.0.0.1:2380"
initial-cluster-state = "new"


lease = 3
log-level = "info"
tso-save-interval = "3s"
max-peer-count = 3


[schedule]
min-region-count = 10
min-leader-count = 10
max-snapshot-count = 3
min-balance-diff-ratio = 0.01
max-store-down-duration = "30m"
leader-schedule-limit = 4
leader-schedule-interval = "30s"
storage-schedule-limit = 4
storage-schedule-interval = "30s"

[metric]
# prometheus client push interval, set "0s" to disable prometheus.
interval = "15s"
# prometheus pushgateway address, leaves it empty will disable prometheus.
address = ""
